#!/usr/bin/env node
/**
 * Patch memdir.js — Add banner image edit overlay in initHeaderEditing().
 *
 * Two patches:
 *   1. Update field classification to distinguish banner vs avatar image fields
 *   2. Add banner overlay + upload modal after the avatar overlay block
 */

const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'assets', 'js', 'memdir.js');
let src = fs.readFileSync(file, 'utf8');

// ── Patch 1: Update field classification ──────────────────────────────────
// Replace the simple "first image = avatar" logic with suffix-based detection.

const oldClassify = [
	'\t\t\t// Classify header fields by type',
	'\t\t\tvar imageField     = null;',
	'\t\t\tvar imageFieldKey  = null;',
	'\t\t\tvar textFields     = [];',
	'\t\t\tvar taxonomyFields = [];',
	'\t\t\tvar socialFields   = [];',
	'',
	"\t\t\tfieldContent.querySelectorAll( '.acf-field[data-key]' ).forEach( function ( field ) {",
	"\t\t\t\tvar key  = field.dataset.key  || '';",
	"\t\t\t\tvar type = field.dataset.type || '';",
	'\t\t\t\tif ( headerFieldKeys.indexOf( key ) === -1 ) { return; }',
	'',
	"\t\t\t\tif ( type === 'image' && ! imageField ) {",
	'\t\t\t\t\timageField    = field;',
	'\t\t\t\t\timageFieldKey = key;',
	"\t\t\t\t} else if ( type === 'text' ) {",
	'\t\t\t\t\ttextFields.push( field );',
	"\t\t\t\t} else if ( type === 'taxonomy' ) {",
	'\t\t\t\t\ttaxonomyFields.push( field );',
	'\t\t\t\t} else if ( isSocialField( field ) ) {',
	'\t\t\t\t\tsocialFields.push( field );',
	'\t\t\t\t}',
	'\t\t\t} );',
	'',
	'\t\t\tvar hasAnyField = imageField || textFields.length || taxonomyFields.length || socialFields.length;',
].join('\r\n');

const newClassify = [
	'\t\t\t// Classify header fields by type.',
	'\t\t\t// Image fields are split into avatar vs banner by ACF field name suffix.',
	'\t\t\tvar AVATAR_SUFFIXES = [ "_photo", "_avatar", "_headshot", "_portrait" ];',
	'\t\t\tvar BANNER_SUFFIXES = [ "_banner", "_cover", "_header_image" ];',
	'',
	'\t\t\tvar imageField     = null;  // avatar',
	'\t\t\tvar imageFieldKey  = null;',
	'\t\t\tvar bannerField    = null;',
	'\t\t\tvar bannerFieldKey = null;',
	'\t\t\tvar textFields     = [];',
	'\t\t\tvar taxonomyFields = [];',
	'\t\t\tvar socialFields   = [];',
	'',
	'\t\t\tfunction endsWithAny( str, suffixes ) {',
	'\t\t\t\tfor ( var i = 0; i < suffixes.length; i++ ) {',
	'\t\t\t\t\tif ( str.length > suffixes[ i ].length && str.substring( str.length - suffixes[ i ].length ) === suffixes[ i ] ) { return true; }',
	'\t\t\t\t}',
	'\t\t\t\treturn false;',
	'\t\t\t}',
	'',
	"\t\t\tfieldContent.querySelectorAll( '.acf-field[data-key]' ).forEach( function ( field ) {",
	"\t\t\t\tvar key  = field.dataset.key  || '';",
	"\t\t\t\tvar type = field.dataset.type || '';",
	"\t\t\t\tvar name = field.dataset.name || '';",
	'\t\t\t\tif ( headerFieldKeys.indexOf( key ) === -1 ) { return; }',
	'',
	"\t\t\t\tif ( type === 'image' ) {",
	'\t\t\t\t\tif ( ! bannerField && endsWithAny( name, BANNER_SUFFIXES ) ) {',
	'\t\t\t\t\t\tbannerField    = field;',
	'\t\t\t\t\t\tbannerFieldKey = key;',
	'\t\t\t\t\t} else if ( ! imageField ) {',
	"\t\t\t\t\t\t// Avatar suffixes or unmatched fallback \u2192 avatar.",
	'\t\t\t\t\t\timageField    = field;',
	'\t\t\t\t\t\timageFieldKey = key;',
	'\t\t\t\t\t}',
	"\t\t\t\t} else if ( type === 'text' ) {",
	'\t\t\t\t\ttextFields.push( field );',
	"\t\t\t\t} else if ( type === 'taxonomy' ) {",
	'\t\t\t\t\ttaxonomyFields.push( field );',
	'\t\t\t\t} else if ( isSocialField( field ) ) {',
	'\t\t\t\t\tsocialFields.push( field );',
	'\t\t\t\t}',
	'\t\t\t} );',
	'',
	'\t\t\tvar hasAnyField = imageField || bannerField || textFields.length || taxonomyFields.length || socialFields.length;',
].join('\r\n');

if ( ! src.includes( oldClassify ) ) {
	console.error('PATCH 1 FAILED: Could not find field classification block.');
	process.exit(1);
}
src = src.replace( oldClassify, newClassify );
console.log('Patch 1 applied: field classification updated with banner/avatar suffix detection.');

// ── Patch 2: Add banner overlay + modal ───────────────────────────────────

const avatarBlockEnd = [
	"\t\t\t\toverlay.addEventListener( 'click', function () { showDialogSafe( avDialog ); } );",
	'\t\t\t}',
	'',
	'\t\t\t// ========================================',
	'\t\t\t// Name \u2014 pencil next to title + modal',
	'\t\t\t// ========================================',
].join('\r\n');

// Build replacement with the banner block inserted between avatar and name sections.
// Use double-quoted strings for lines containing single quotes to avoid escaping issues.
const bannerBlock = [
	"\t\t\t\toverlay.addEventListener( 'click', function () { showDialogSafe( avDialog ); } );",
	'\t\t\t}',
	'',
	'\t\t\t// ========================================',
	"\t\t\t// Banner \u2014 camera overlay + modal",
	'\t\t\t// ========================================',
	"\t\t\t" + 'var bannerDiv = headerWrap.querySelector( ".memdir-header__banner" );',
	'\t\t\tif ( bannerField && bannerDiv ) {',
	"\t\t\t\tbannerField.style.display = 'none';",
	'',
	"\t\t\t\t" + 'var bnAcfInput  = bannerField.querySelector( \'input[type="hidden"]\' );',
	"\t\t\t\tvar bnHasImage  = bnAcfInput && bnAcfInput.value && bnAcfInput.value !== '0';",
	'',
	'\t\t\t\t// Camera overlay on the banner div',
	"\t\t\t\tvar bnOverlay = document.createElement( 'div' );",
	"\t\t\t\tbnOverlay.className = 'memdir-header__banner-edit';",
	"\t\t\t\tbnOverlay.innerHTML = cameraSvg + '<span>' + ( bnHasImage ? 'Change Banner' : 'Add Banner' ) + '</span>';",
	"\t\t\t\tbnOverlay.title = bnHasImage ? 'Change banner image' : 'Add a banner image';",
	'\t\t\t\tbannerDiv.appendChild( bnOverlay );',
	'',
	'\t\t\t\t// Build modal content',
	"\t\t\t\tvar bnFragment = document.createElement( 'div' );",
	'',
	"\t\t\t\tvar bnPreview = document.createElement( 'img' );",
	"\t\t\t\tbnPreview.className = 'memdir-header-modal__banner-preview';",
	"\t\t\t\tbnPreview.src = bnHasImage && bannerDiv.style.backgroundImage",
	"\t\t\t\t\t? bannerDiv.style.backgroundImage.replace( /^url\\([\"']?/, '' ).replace( /[\"']?\\)$/, '' )",
	"\t\t\t\t\t: '';",
	"\t\t\t\tbnPreview.alt = 'Current banner';",
	"\t\t\t\tif ( ! bnHasImage ) { bnPreview.style.display = 'none'; }",
	'\t\t\t\tbnFragment.appendChild( bnPreview );',
	'',
	"\t\t\t\tvar bnStatus = document.createElement( 'p' );",
	"\t\t\t\tbnStatus.className = 'memdir-header-modal__avatar-status';",
	"\t\t\t\tbnStatus.textContent = '';",
	'\t\t\t\tbnFragment.appendChild( bnStatus );',
	'',
	"\t\t\t\tvar bnFileInput = document.createElement( 'input' );",
	"\t\t\t\tbnFileInput.type = 'file';",
	"\t\t\t\tbnFileInput.accept = 'image/*';",
	"\t\t\t\tbnFileInput.style.display = 'none';",
	'\t\t\t\tbnFragment.appendChild( bnFileInput );',
	'',
	"\t\t\t\tvar bnUploadBtn = document.createElement( 'button' );",
	"\t\t\t\tbnUploadBtn.type = 'button';",
	"\t\t\t\tbnUploadBtn.className = 'memdir-header-modal__avatar-btn';",
	"\t\t\t\tbnUploadBtn.textContent = 'Choose Banner Image';",
	'\t\t\t\tbnFragment.appendChild( bnUploadBtn );',
	'',
	"\t\t\t\tvar bnDeleteBtn = document.createElement( 'button' );",
	"\t\t\t\tbnDeleteBtn.type = 'button';",
	"\t\t\t\tbnDeleteBtn.className = 'memdir-header-modal__avatar-btn memdir-header-modal__avatar-btn--delete';",
	"\t\t\t\tbnDeleteBtn.textContent = 'Remove Banner';",
	"\t\t\t\tif ( ! bnHasImage ) { bnDeleteBtn.style.display = 'none'; }",
	'\t\t\t\tbnFragment.appendChild( bnDeleteBtn );',
	'',
	'\t\t\t\t// Delete handler',
	"\t\t\t\tbnDeleteBtn.addEventListener( 'click', function () {",
	"\t\t\t\t\tif ( ! confirm( 'Remove the banner image?' ) ) { return; }",
	'',
	"\t\t\t\t\tbnStatus.textContent = 'Removing\\u2026';",
	'\t\t\t\t\tbnDeleteBtn.disabled = true;',
	'\t\t\t\t\tbnUploadBtn.disabled = true;',
	'',
	'\t\t\t\t\tvar fd = new FormData();',
	"\t\t\t\t\tfd.append( 'action',  'md_save_section' );",
	"\t\t\t\t\tfd.append( 'nonce',   window.mdAjax.nonce );",
	"\t\t\t\t\tfd.append( 'post_id', postId );",
	"\t\t\t\t\tfd.append( 'acf[' + bannerFieldKey + ']', '' );",
	'',
	"\t\t\t\t\tfetch( window.mdAjax.ajaxurl, { method: 'POST', body: fd } )",
	"\t\t\t\t\t\t.then( function ( r ) { return r.json(); } )",
	'\t\t\t\t\t\t.then( function ( res ) {',
	'\t\t\t\t\t\t\tif ( res.success ) {',
	"\t\t\t\t\t\t\t\tbnPreview.src = '';",
	"\t\t\t\t\t\t\t\tbnPreview.style.display = 'none';",
	"\t\t\t\t\t\t\t\tbannerDiv.style.backgroundImage = '';",
	"\t\t\t\t\t\t\t\tbannerDiv.classList.add( 'memdir-header__banner--empty' );",
	"\t\t\t\t\t\t\t\tbnStatus.textContent = 'Banner removed.';",
	"\t\t\t\t\t\t\t\tbnDeleteBtn.style.display = 'none';",
	"\t\t\t\t\t\t\t\tbnOverlay.innerHTML = cameraSvg + '<span>Add Banner</span>';",
	"\t\t\t\t\t\t\t\tif ( bnAcfInput ) { bnAcfInput.value = ''; }",
	'\t\t\t\t\t\t\t} else {',
	"\t\t\t\t\t\t\t\tbnStatus.textContent = 'Error: ' + ( res.data && res.data.message ? res.data.message : 'Remove failed.' );",
	'\t\t\t\t\t\t\t}',
	'\t\t\t\t\t\t\tbnDeleteBtn.disabled = false;',
	'\t\t\t\t\t\t\tbnUploadBtn.disabled = false;',
	'\t\t\t\t\t\t} )',
	"\t\t\t\t\t\t.catch( function () {",
	"\t\t\t\t\t\t\tbnStatus.textContent = 'Network error.';",
	'\t\t\t\t\t\t\tbnDeleteBtn.disabled = false;',
	'\t\t\t\t\t\t\tbnUploadBtn.disabled = false;',
	'\t\t\t\t\t\t} );',
	'\t\t\t\t} );',
	'',
	"\t\t\t\tvar bnDialog = createMiniModal( 'Update Banner', [], {",
	'\t\t\t\t\tcustomContent: bnFragment,',
	"\t\t\t\t\tmodifier: 'banner',",
	'\t\t\t\t\tnoSave: true',
	'\t\t\t\t} );',
	'',
	"\t\t\t\tbnUploadBtn.addEventListener( 'click', function () { bnFileInput.click(); } );",
	"\t\t\t\tbnFileInput.addEventListener( 'change', function () {",
	'\t\t\t\t\tvar file = bnFileInput.files[ 0 ];',
	'\t\t\t\t\tif ( ! file ) { return; }',
	'',
	"\t\t\t\t\tbnStatus.textContent = 'Uploading\\u2026';",
	'\t\t\t\t\tbnUploadBtn.disabled = true;',
	'',
	'\t\t\t\t\tvar fd = new FormData();',
	"\t\t\t\t\tfd.append( 'action',    'memdir_ajax_upload_avatar' );",
	"\t\t\t\t\tfd.append( 'nonce',     window.mdAjax.nonce );",
	"\t\t\t\t\tfd.append( 'post_id',   postId );",
	"\t\t\t\t\tfd.append( 'field_key', bannerFieldKey );",
	"\t\t\t\t\tfd.append( 'image',     file );",
	'',
	"\t\t\t\t\tfetch( window.mdAjax.ajaxurl, { method: 'POST', body: fd } )",
	"\t\t\t\t\t\t.then( function ( r ) { return r.json(); } )",
	'\t\t\t\t\t\t.then( function ( res ) {',
	'\t\t\t\t\t\t\tif ( res.success && res.data && res.data.url ) {',
	'\t\t\t\t\t\t\t\tbnPreview.src = res.data.url;',
	"\t\t\t\t\t\t\t\tbnPreview.style.display = '';",
	"\t\t\t\t\t\t\t\tbannerDiv.style.backgroundImage = 'url(' + res.data.url + ')';",
	"\t\t\t\t\t\t\t\tbannerDiv.classList.remove( 'memdir-header__banner--empty' );",
	"\t\t\t\t\t\t\t\tbnStatus.textContent = 'Banner updated.';",
	"\t\t\t\t\t\t\t\tbnDeleteBtn.style.display = '';",
	"\t\t\t\t\t\t\t\tbnOverlay.innerHTML = cameraSvg + '<span>Change Banner</span>';",
	'\t\t\t\t\t\t\t\tif ( bnAcfInput && res.data.id ) { bnAcfInput.value = res.data.id; }',
	'\t\t\t\t\t\t\t} else {',
	"\t\t\t\t\t\t\t\tbnStatus.textContent = 'Error: ' + ( res.data && res.data.message ? res.data.message : 'Upload failed.' );",
	'\t\t\t\t\t\t\t}',
	'\t\t\t\t\t\t\tbnUploadBtn.disabled = false;',
	"\t\t\t\t\t\t\tbnFileInput.value = '';",
	'\t\t\t\t\t\t} )',
	"\t\t\t\t\t\t.catch( function () {",
	"\t\t\t\t\t\t\tbnStatus.textContent = 'Network error.';",
	'\t\t\t\t\t\t\tbnUploadBtn.disabled = false;',
	"\t\t\t\t\t\t\tbnFileInput.value = '';",
	'\t\t\t\t\t\t} );',
	'\t\t\t\t} );',
	'',
	"\t\t\t\tbnOverlay.addEventListener( 'click', function () { showDialogSafe( bnDialog ); } );",
	'\t\t\t}',
	'',
	'\t\t\t// ========================================',
	"\t\t\t// Name \u2014 pencil next to title + modal",
	'\t\t\t// ========================================',
].join('\r\n');

if ( ! src.includes( avatarBlockEnd ) ) {
	console.error('PATCH 2 FAILED: Could not find avatar block end marker.');
	process.exit(1);
}
src = src.replace( avatarBlockEnd, bannerBlock );
console.log('Patch 2 applied: banner overlay + upload modal added.');

fs.writeFileSync( file, src, 'utf8' );
console.log('Done. File saved.');
